### ISSUE TITLE
Add linux aarch64 builds

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/mafft-feedstock#4]
### Comment:

To make nextstrain's augur work on aarch64, we need mafft builds that work for aarch64

**Comment by hmacdope** [comment]
Let me know if that works for you now (after CDN rolls out)

**Comment by corneliusroemer** [comment]
Resolved by https://github.com/conda-forge/mafft-feedstock/pull/7

Thanks @hmacdope - big thanks to the iqtree folks as well for making it so seamless to cross compile! Amazing job.
